# Configuration file paths
server.details.path=src/main/resources/serverDetails.json
clientNode.details.path=src/main/resources/clientDetails.json
transactions.sets.path=src/main/resources/transactionSets.csv
client.timeout.millis=6000
server.timeout.millis=3000
view.change.timeout.millis=2000
malice.time.delay.millis=1000
max.retries=1
checkpoint.interval=10
watermark.window=50
private.key.dir=keys/private/
public.key.path=keys/manifest.json