syntax = "proto3";

import "google/protobuf/empty.proto";

option java_package = "org.example";

service MessageService {

    // for clientNode
    rpc Request (ClientRequest) returns (google.protobuf.Empty) {}; // analogous to the invoke operation in PBFT
    rpc Reply (ClientReply) returns (google.protobuf.Empty) {};

    // for PBFT
    rpc PrePrepare(PrePrepareRequest) returns (google.protobuf.Empty);
    rpc Prepare(PrepareMessage) returns (google.protobuf.Empty);
    rpc Commit(CommitMessage) returns (google.protobuf.Empty);

    // checkpointing
    rpc Checkpoint(CheckpointMessage) returns (google.protobuf.Empty);
    rpc StateRequest(StateRequestMessage) returns (google.protobuf.Empty);
    rpc StateResponse(StateMessage) returns (google.protobuf.Empty);

    // view change
    rpc ViewChange(ViewChangeMessage) returns (google.protobuf.Empty);
    rpc NewView(NewViewMessage) returns (google.protobuf.Empty);
    rpc GetClientRequest(SequenceNumber) returns (google.protobuf.Empty);

    // for cli
    rpc SetActiveFlag(ActiveFlag) returns (Acknowledgement);
    rpc Reset(google.protobuf.Empty) returns (Acknowledgement) {};
    rpc GetLog(google.protobuf.Empty) returns (CLIResponse) {};
    rpc GetDB(google.protobuf.Empty) returns (CLIResponse) {};
    rpc GetStatus(SequenceNumber) returns (CLIResponse) {};
    rpc GetNewViews(google.protobuf.Empty) returns (CLIResponse) {};
    rpc GetOperationLog(google.protobuf.Empty) returns (CLIResponse) {};
    rpc InjectMalice(Malice) returns (Acknowledgement) {};
}



// CLI to server request

message ActiveFlag {
    bool active_flag = 1;
}

message Acknowledgement {
    bool status = 1;
}

message SequenceNumber {
    int64 sequence_number = 1;
}

message CLIResponse {
    string cli_response = 1;
}

message Malice {
    string malice_type = 1;
    repeated string malicious_server_id = 2;
    repeated string target_server_id = 3;
}

// Client to server request

message Transfer {
  string sender = 1;
  string receiver = 2;
  double amount = 3;
}

message BalanceRequest {
  string account_id = 1;
}

message Operation {
  oneof op {
    Transfer transfer = 1;
    BalanceRequest balance_request = 2;
  }
}

message OperationResult {
  oneof op {
    bool result = 1;
    double balance = 2;
  }
}

message ClientRequest {
  Operation operation = 1;
  int64 timestamp = 2;
  string client_id = 3;
  string signer_id = 4;
  bytes signature = 5;
  bool is_read_only = 6;
}

// Server to client reply

message ClientReply {
  int64 view_number = 1;
  int64 timestamp = 2;
  string client_id = 3;
  string server_id = 4;
  OperationResult result = 5;
  string signer_id = 6;
  bytes signature = 7;
}

message PrePrepareMessage {
    int64 view_number = 1;
    int64 sequence_number = 2;
    bytes digest = 3;
    string signer_id = 4;
    bytes signature = 5;
}

message PrePrepareRequest {
    PrePrepareMessage pre_prepare_message = 1;
    ClientRequest request = 2;
}

message PrepareMessage {
    int64 view_number = 1;
    int64 sequence_number = 2;
    bytes digest = 3;
    bool is_aggregated = 4;
    string signer_id = 5;
    bytes signature = 6;
}

message CommitMessage {
    int64 view_number = 1;
    int64 sequence_number = 2;
    bytes digest = 3;
    bool is_aggregated = 4;
    string signer_id = 5;
    bytes signature = 6;
}

// checkpointing

message CheckpointMessage {
    int64 view_number = 1;
    int64 sequence_number = 2;
    bytes digest = 3;
    string signer_id = 4;
    bytes signature = 5;
}

message StateRequestMessage {
    string requester_id = 1;
}

message StateMessage {
    map<string, double> state_snapshot = 1;
    bytes digest = 2;
    string signer_id = 3;
    bytes signature = 4;
}

// view change

message PreparedCertificate {
    PrePrepareMessage pre_prepare_message = 1;
    PrepareMessage prepare_message = 2;
}

message ViewChangeMessage {
    int64 view_number = 1;
    int64 last_stable_sequence_number = 2;
    repeated CheckpointMessage checkpoint_messages = 3;
    repeated PreparedCertificate prepared_certificates = 4;
    string signer_id = 5;
    bytes signature = 6;
}

message NewViewMessage {
    int64 view_number = 1;
    repeated ViewChangeMessage view_change_messages = 2;
    repeated PrePrepareMessage pre_prepare_messages = 3;
    string signer_id = 4;
    bytes signature = 5;
}